### ISSUE TITLE
一直无限循环报错下去

### ISSUE THREAD

**Issue by 986138497** [jezzmemo/JJException#108] opened 2021-09-10 08:55 UTC
**Describe the bug**

**To Reproduce**

**Please complete the following information**
 - Device: [e.g. iPhone 所有]
 - OS: [e.g. iOS 14]

**Comment by jezzmemo** [comment] 2021-09-14 14:23
什么意思？

**Comment by jezzmemo** [comment] 2021-09-28 02:34
Duplicate of #111

**Closed** 2021-09-30 15:20 UTC
